Add first_lab
Svjatoslav/Os_labs pull request #1
Opened 2023-10-25 16:16 UTC by Svjatoslav

2023-10-27 22:05 UTC, DariaWelt requested changes
Демон не изменяет рабочую дерикторию.

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +bool Daemon::write_pid(std::string out_pid) {
В функуцию семантически нужно передавать число, а не строку(тем более по значению, а не по ссылке)

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +            return 2;
Почему 2?

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +double Daemon::read_pid() {
pid(process id) - это целое число. Конвертировать его в число с плавающей точкой нельзя, так как это не биекция и может вызвать ошибку.

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    else {return false;}
Нужно убрать else, а оставить просто return

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.h
> +    static inline std::vector<std::string> data = {};
Зачем эти поля статические, если они явно относятся к экземпляру класса?

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +#include "daemon.h"
Уберите лишние инклуды

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    double ex_pid = read_pid();
bool имеет только 2 значения true и false, замените в вашей программе все места, где присваиваете ему целые значения. Это работает, потому что происходит неявный каст от int в bool, но он работает так, что все, что не 0 будет восприниматься как true.

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/first_folder/wrewrwe.txt
папок first_folder и second_folder вообще не должно быть, как и файла pid.txt

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    if (dir) {return true;}
У вас уже dir кастится к bool. Зачем if?

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    pid_t pid = fork();
fork возвращаяет -1 в случе ошибки и ненулевой результат для родительского процесса, у вас это не учтено.

2023-10-27 22:05 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    std::ofstream outputFile(filePath, std::ios::trunc);  // clean file and then write
файл с пидом нужно хранить в папке /var/run, чтобы демон не зависел от этой директории

2023-11-05 21:00 UTC, Svjatoslav commented on Lab_1/daemon.h
> +    static inline std::vector<std::string> data = {};
1) У нас singleton, поэтому, как будто, неважно статическое поле или нет (т.к экземпляр класса существует в единственном виде)
2) Без статика не компилируется 😢

2023-11-05 21:24 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +            return 2;
В функции reset_new_process двойка обрабатывается (до этого была опечатка)

2023-11-06 14:27 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    std::ofstream outputFile(filePath, std::ios::trunc);  // clean file and then write
Исправил

2023-11-06 14:28 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    pid_t pid = fork();
Исправил

2023-11-06 14:28 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    if (dir) {return true;}
Исправил

2023-11-06 14:28 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    else {return false;}
Исправил

2023-11-06 14:29 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    double ex_pid = read_pid();
Исправил

2023-11-06 14:33 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +#include "daemon.h"
Исправил

2023-11-06 14:54 UTC, Svjatoslav commented on Lab_1/first_folder/wrewrwe.txt
Исправил

2023-11-06 14:57 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +bool Daemon::write_pid(std::string out_pid) {
Исправил

2023-11-06 14:58 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    std::ofstream outputFile(filePath, std::ios::trunc);  // clean file and then write
Демон меняет директорию

2023-11-08 09:24 UTC, DariaWelt requested changes
демон сразу крашится. Исправьте.
```
ноя 08 12:19:03 daria-0-1 daemon_executable[143053]: FILE HAS OPENED
ноя 08 12:19:03 daria-0-1 daemon_executable[143053]: READ_PID
ноя 08 12:19:03 daria-0-1 daemon_executable[143053]: CHECK PROCESS EXISTS
ноя 08 12:19:03 daria-0-1 daemon_executable[143053]: ERROR WITH CONFIG FILE. EXIT.
```

Вот конфиг
```
(base) daria@daria-0-1:~/Downloads/Os_labs-first_lab/Lab_1$ cat config.txt 
/home/daria/Downloads/Os_labs-first_lab/Lab_1/folder2
/home/daria/Downloads/Os_labs-first_lab/Lab_1/folder1
```

должен еще уметь обрабатывать относительные пути:
```
(base) daria@daria-0-1:~/Downloads/Os_labs-first_lab/Lab_1$ cat config.txt 
./folder2
./folder1
```

2023-11-08 09:24 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    std::string filename = "/var/run/my_daemon.pid";
используйте pid_file_path константу

2023-11-08 09:24 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    std::string filename = "/var/run/my_daemon.pid";
то же самое: pid_file_path константа

2023-11-08 09:24 UTC, DariaWelt commented on Lab_1/daemon.cpp
> +    std::string filename = "/home/vboxuser/Desktop/Lab1/config.txt";
у меня такого файла нет:( Демон падает. 
Сделайте везде поддержку относительных путей, сохраняйте их как абсолютные 
https://en.cppreference.com/w/cpp/filesystem/absolute

2023-11-08 09:24 UTC, DariaWelt commented on Lab_1/build.sh
> +sudo ./daemon_executable
удалите эту строку

2023-11-10 11:14 UTC, Svjatoslav commented on Lab_1/build.sh
> +sudo ./daemon_executable
Исправил

2023-11-10 11:18 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    std::string filename = "/var/run/my_daemon.pid";
Исправил

2023-11-10 11:18 UTC, Svjatoslav commented on Lab_1/daemon.cpp
> +    std::string filename = "/var/run/my_daemon.pid";
Исправил

2023-11-10 12:31 UTC, Svjatoslav commented
Добрый день, сделал все правки кроме "Должен уметь обрабатывать относительные пути". 
Демон меняет директорию на root. Из этого вопрос: Пути относительный относительно директории в который лежит config.txt ? Если так, то это кажется странным требованием, ведь конфиг совсем необязательно должен находиться в той же директории, что и папки (folder1, folder2).

2023-11-12 09:17 UTC, DariaWelt requested changes

2023-11-12 09:17 UTC, DariaWelt commented on Lab_1/daemon_executable
Работа зачтена. Уберите этот бинарник, перезапросите ревью, и я смержу

2023-11-12 20:33 UTC, DariaWelt approved these changes

2023-11-12 20:34 UTC, merged