Second lab
Svjatoslav/Os_labs pull request #2
Opened 2023-12-01 11:10 UTC by Svjatoslav

Реализован только один тип взаимодействия.

2023-12-09 12:20 UTC, DariaWelt requested changes
Поправьте cmake. Могу зачесть работу на пониженный балл

2023-12-09 12:20 UTC, DariaWelt commented on Lab_2/CMakeLists.txt
> +find_package (Threads)
Если используете std многопоточность, то зачем тогда это?

2023-12-09 16:41 UTC, Svjatoslav commented on Lab_2/CMakeLists.txt
> +find_package (Threads)
std многопоточность использовал только для очереди и асинхронного ввода, в остальном использовал p-thread'ы

2023-12-09 16:43 UTC, Svjatoslav commented
Зачтите на пониженный балл, пожалуйста 🤝

2023-12-10 10:07 UTC, DariaWelt approved these changes
зачтено

2023-12-10 10:07 UTC, merged